<a href="https://colab.research.google.com/github/ShivanshGupta1/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NumPy is a Python library used for working with arrays.
#In Python we have lists that serve the purpose of arrays, but they are slow to process.
#NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

import numpy as np
arr = np.array([2,1,3,5,2])
print(arr, type(arr))

NoDimensionList = np.array(0)
print(NoDimensionList, NoDimensionList.ndim)

OneDList = np.array([1,3,4,5])
print(OneDList, OneDList.ndim)

TwoDList = np.array([[23,5,2,5],[12,2,4,6],[12,2,4,1]])
print(TwoDList, TwoDList.ndim)

ThreeDList = np.array([[[23,5,2,5],[12,2,4,6],[12,2,4,1]],[[23,5,2,5],[12,2,4,6],[12,2,4,1]]])
print(ThreeDList, ThreeDList.ndim)

OneDList2 = np.array([1,3,4,5],ndmin=5)
print(OneDList2, OneDList2.ndim)

OneDList3 = np.array([1,3,4,5])
print(OneDList3[1]+OneDList3[2])

TwoDList1 = np.array([[23,5,2,5],[12,2,4,6],[12,2,4,1]])
print(TwoDList1[1][3])

[2 1 3 5 2] <class 'numpy.ndarray'>
0 0
[1 3 4 5] 1
[[23  5  2  5]
 [12  2  4  6]
 [12  2  4  1]] 2
[[[23  5  2  5]
  [12  2  4  6]
  [12  2  4  1]]

 [[23  5  2  5]
  [12  2  4  6]
  [12  2  4  1]]] 3
[[[[[1 3 4 5]]]]] 5
7
6
[6, 7]


In [ ]:
#Slicing in arrays
import numpy as np
myArrary = np.array([2,4,5,7,8,4])
print(myArrary[1:5:2]) #Start:End:Steps

#Sorted array (even numbers)
myArrary = np.array([1,2,3,4,5,6])
print(myArrary[1:6:2])

#Reverse array
print(myArrary[::-1])

#2D array
myArrary = np.array([[2,3,4,5],[6,7,8,9,10]])
print(myArrary[1][0:3])

#Copy and View

myArrary = np.array([1,2,3,4,5,7])
copyArray = myArrary.copy() #Will create a copy, but won't reference to the same variable
print(copyArray)
myArrary[5] = 9
print(copyArray)
print(myArrary)
print("view")#Will reflect changes
copyArray2 = myArrary.view()
myArrary[1] = 4
print(myArrary)
print(copyArray2)

[4 7]
[2 4 6]
[6 5 4 3 2 1]
[6, 7, 8]
[1 2 3 4 5 7]
[1 2 3 4 5 7]
[1 2 3 4 5 9]
view
[1 4 3 4 5 9]
[1 4 3 4 5 9]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [ ]:
#Shape
import numpy as np
TwoDArray = np.array([[3,4,2,4],[3,4,2,4]])#(Number of lists in each dimension, Elements in each list)
print(TwoDArray.shape)
OneDArray = np.array([3,4,2,4])
print(OneDArray.shape)
myTupple = (4,) #For a tuple
print(type(myTupple))

(2, 4)
(4,)
<class 'tuple'>


In [ ]:
#Reshape
import numpy as np
OneDArray = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
myVar = OneDArray.reshape(4,3) #Will only reshape, when the values are divisble, otherwise, will give error
print(myVar)
ThreeDArray = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
copyVar = ThreeDArray.reshape(2,3,2)#Length = dimension of the array -> Multiply all numbers to check
print(copyVar)
print(copyVar.ndim)
print("Iteration")
#Iteration
for i in OneDArray:
  print(i)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
Iteration
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#HW
import numpy as np
OneDArray = np.array([1,2,3,4,5,6,7,8])
myVar = OneDArray.reshape(2,4)
myVar2 = OneDArray.reshape(4,1,1,2) #The first divides, into 4 sub arrays, then the next 1 denotes to make the entire list 1 again by adding a bracket, then it repeats that again and then the last 2 determines the number of elements in each list
print(myVar)
print(myVar2)
#convert 1-D array of len(8) into 2d,4d
OneDArray = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])
myVar = OneDArray.reshape(3,3,3)#The number of elements, determin the dimension. The number should be broken its dimension, and its product should be the length
print(myVar)
#convert 1-D array of len(27) into 3d

[[1 2 3 4]
 [5 6 7 8]]
[[[[1 2]]]


 [[[3 4]]]


 [[[5 6]]]


 [[[7 8]]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
#Array Math
#i - integer
#b - boolean
#u - unsigned integer ("mixed data types")
#f - float
#c - complex float
#s- string
#o - object
#U - Unicode string
import numpy as np
array1 = np.array([[1,3,4,6,7],[3,2,5,7,2]]) #prints int64 - int as all the data types are int and 64, as the memory can store 64 bits
print(array1.dtype,)
array1 = np.array(["aD","DSA","DSA"]) 
print(array1)
print(array1.dtype,)
array1 = np.array([232.23,"asds",23, True, 232.223,12.24]) 
print(array1.dtype,)
array1 = np.array("A")
print(array1.dtype)
array1 = np.array([232.23,232.223,12.24],dtype= "i")
print(array1) 

int64
['aD' 'DSA' 'DSA']
<U3
<U32
<U1
[232 232  12]


In [ ]:
#Covert 2 dimensional array (Array Math)
import numpy as np

firstArray = np.array([[2,4,6,8,9,4],[2,4,1,3,5,6]])#All the number of elements should be same
secondArray = np.array([[6,4,7,8,4,5],[6,2,6,8,4,3]])
print(firstArray+secondArray)#This will concatinate, not add

# + operator

print(np.add(firstArray,secondArray))

# - operator

print(firstArray-secondArray)
print(np.subtract(firstArray,secondArray))

# * operator

print(firstArray*secondArray)
print(np.multiply(firstArray,secondArray))

# / operator

print(firstArray/secondArray)
print(np.divide(firstArray,secondArray))

# sq. root
print(np.sqrt(firstArray))



[[ 8  8 13 16 13  9]
 [ 8  6  7 11  9  9]]
[[ 8  8 13 16 13  9]
 [ 8  6  7 11  9  9]]
[[-4  0 -1  0  5 -1]
 [-4  2 -5 -5  1  3]]
[[-4  0 -1  0  5 -1]
 [-4  2 -5 -5  1  3]]
[[12 16 42 64 36 20]
 [12  8  6 24 20 18]]
[[12 16 42 64 36 20]
 [12  8  6 24 20 18]]
[[0.33333333 1.         0.85714286 1.         2.25       0.8       ]
 [0.33333333 2.         0.16666667 0.375      1.25       2.        ]]
[[0.33333333 1.         0.85714286 1.         2.25       0.8       ]
 [0.33333333 2.         0.16666667 0.375      1.25       2.        ]]
[[1.41421356 2.         2.44948974 2.82842712 3.         2.        ]
 [1.41421356 2.         1.         1.73205081 2.23606798 2.44948974]]
[0.1493267  0.87278965 0.71407572 0.58219684 0.74836575 0.92113807
 0.55193836 0.84414809 0.91924073 0.37402699]


In [ ]:
#random array

myarray = np.random.random(10)#1D array of 10 elements
print(myarray)
myarray = np.random.random((2,2))#2D array of 2 elements each, (number of lists, number of items)
print(myarray)

[0.08450815 0.00193162 0.67884392 0.36640199 0.13937839 0.58442744
 0.58389927 0.55813718 0.12194173 0.08307989]
[[0.52855232 0.17281109]
 [0.28703023 0.66931349]
 [0.49399321 0.17383373]]


In [ ]:
#Concatenate with 1d array
array1 = np.array([1,2,3,5,6,7])
array2 = np.array([1,2,3,5,6,8,32,32])
myVar = np.concatenate((array1,array2))
print(myVar)
#Concatenate with 2d array
array1 = np.array([[1,2,3,5,6,7],[1,2,3,5,6,7]])
array2 = np.array([[1,2,3,5,6,7],[1,2,3,5,6,7]])
myVar = np.concatenate((array1,array2)) #For 2d array we need same length
print(myVar)

[ 1  2  3  5  6  7  1  2  3  5  6  8 32 32]
[[1 2 3 5 6 7]
 [1 2 3 5 6 7]
 [1 2 3 5 6 7]
 [1 2 3 5 6 7]]


In [ ]:
#Split
array1 = np.array([1,2,3,5,6,7])
myVar = np.array_split(array1,4)#split array into - (array, by how much to split)
print(myVar)

[array([1, 2]), array([3, 5]), array([6]), array([7])]


In [ ]:
#Sort
array1 = np.array([3,4,5,2,1,35,32])
print(np.sort(array1))#How to sort a array
array2 = np.array([[2,3,4,5],[12,3,4,2]])
print(np.sort(array2))

[ 1  2  3  4  5 32 35]
[[ 2  3  4  5]
 [ 2  3  4 12]]
